# Generated by Django 3.2 on 2023-02-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_description_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Место', to='places.place', verbose_name='Место')),
            ],
        ),
    ]
