# Generated by Django 3.2 on 2023-02-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details_url',
            field=models.CharField(default='path', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
