# Generated by Django 3.2 on 2023-02-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20230208_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_id',
            new_name='slug',
        ),
    ]
