# Generated by Django 3.2 on 2023-02-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_rename_place_id_place_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='details_url',
        ),
    ]
