# Generated by Django 3.2 on 2023-02-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_details_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('number',)},
        ),
    ]
