# Generated by Django 3.2 on 2023-02-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_remove_place_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
