# Generated by Django 4.1.7 on 2023-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0012_auto_20230214_1153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="number",
            field=models.IntegerField(blank=True, default=0, verbose_name="Позиция"),
        ),
    ]
